In [ ]:
 #Importing pandas library
import pandas as pd
#Loading data into a DataFrame
data_frame=pd.read_csv('/content/drive/MyDrive/SDGP Implementation/data.csv')

In [ ]:
#displaying first five rows
data_frame.head()

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Desired_Savings,Disposable_Income,Potential_Savings_Groceries,Potential_Savings_Transport,Potential_Savings_Eating_Out,Potential_Savings_Entertainment,Potential_Savings_Utilities,Potential_Savings_Healthcare,Potential_Savings_Education,Potential_Savings_Miscellaneous
0,44637.249636,49,0,Self_Employed,Tier_1,13391.174891,0.000000,2206.490129,6658.768341,2636.970696,...,6200.537192,11265.627707,1685.696222,328.895281,465.769172,195.151320,678.292859,67.682471,0.000000,85.735517
1,26858.596592,34,2,Retired,Tier_2,5371.719318,0.000000,869.522617,2818.444460,1543.018778,...,1923.176434,9676.818733,540.306561,119.347139,141.866089,234.131168,286.668408,6.603212,56.306874,97.388606
2,50367.605084,35,1,Student,Tier_3,7555.140763,4612.103386,2201.800050,6313.222081,3221.396403,...,7050.360422,13891.450624,1466.073984,473.549752,410.857129,459.965256,488.383423,7.290892,106.653597,138.542422
3,101455.600247,21,0,Self_Employed,Tier_3,15218.340037,6809.441427,4889.418087,14690.149363,7106.130005,...,16694.965136,31617.953615,1875.932770,762.020789,1241.017448,320.190594,1389.815033,193.502754,0.000000,296.041183
4,24875.283548,52,4,Professional,Tier_2,4975.056710,3112.609398,635.907170,3034.329665,1276.155163,...,1874.099434,6265.700532,788.953124,68.160766,61.712505,187.173750,194.117130,47.294591,67.388120,96.557076

In [ ]:
# Program to print all the column names of the data_frame
list(data_frame.columns)

['Income',
 'Age',
 'Dependents',
 'Occupation',
 'City_Tier',
 'Rent',
 'Loan_Repayment',
 'Insurance',
 'Groceries',
 'Transport',
 'Eating_Out',
 'Entertainment',
 'Utilities',
 'Healthcare',
 'Education',
 'Miscellaneous',
 'Desired_Savings_Percentage',
 'Desired_Savings',
 'Disposable_Income',
 'Potential_Savings_Groceries',
 'Potential_Savings_Transport',
 'Potential_Savings_Eating_Out',
 'Potential_Savings_Entertainment',
 'Potential_Savings_Utilities',
 'Potential_Savings_Healthcare',
 'Potential_Savings_Education',
 'Potential_Savings_Miscellaneous']

In [ ]:
data_frame.describe()

,Income,Age,Dependents,Rent,Loan_Repayment,Insurance,Groceries,Transport,Eating_Out,Entertainment,...,Desired_Savings,Disposable_Income,Potential_Savings_Groceries,Potential_Savings_Transport,Potential_Savings_Eating_Out,Potential_Savings_Entertainment,Potential_Savings_Utilities,Potential_Savings_Healthcare,Potential_Savings_Education,Potential_Savings_Miscellaneous
count,2.000000e+04,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,...,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,4.158550e+04,41.031450,1.995950,9115.494629,2049.800292,1455.028761,5205.667493,2704.466685,1461.856982,1448.853658,...,4982.878416,10647.367257,912.197183,473.042650,254.963280,254.031058,436.332808,41.524964,62.417083,144.904987
std,4.001454e+04,13.578725,1.417616,9254.228188,4281.789941,1492.938435,5035.953689,2666.345648,1481.660811,1489.019270,...,7733.468188,11740.637289,1038.884968,537.222853,296.047943,299.973590,503.200658,53.152458,98.842656,169.160951
min,1.301187e+03,18.000000,0.000000,235.365692,0.000000,30.002012,154.078240,81.228584,39.437523,45.421469,...,0.000000,-5400.788673,16.575501,8.268076,3.797926,3.121610,6.200297,0.001238,0.000000,2.091973
25%,1.760488e+04,29.000000,1.000000,3649.422246,0.000000,580.204749,2165.426419,1124.578012,581.011801,581.632906,...,1224.932636,3774.894323,317.811000,161.913751,84.506870,84.562090,148.013618,11.037421,4.926210,47.637307
50%,3.018538e+04,41.000000,2.000000,6402.751824,0.000000,1017.124681,3741.091535,1933.845509,1029.109726,1020.198376,...,2155.356763,7224.890977,607.038735,307.045856,164.927660,164.740232,285.739582,25.202124,33.127987,93.090257
75%,5.176545e+04,53.000000,3.000000,11263.940492,2627.142320,1787.160895,6470.892718,3360.597508,1807.075251,1790.104082,...,6216.309609,13331.950716,1128.681837,588.419602,313.398240,310.927935,538.983703,52.353736,80.946145,178.257981
max,1.079728e+06,64.000000,4.000000,215945.674703,123080.682009,38734.932935,119816.898124,81861.503457,34406.100166,38667.368308,...,245504.485208,377060.218482,34894.644404,12273.258242,5573.036433,6222.200913,8081.799518,1394.531049,3647.244243,4637.951137

In [ ]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 27 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Income                           20000 non-null  float64
 1   Age                              20000 non-null  int64
 2   Dependents                       20000 non-null  int64
 3   Occupation                       20000 non-null  object
 4   City_Tier                        20000 non-null  object
 5   Rent                             20000 non-null  float64
 6   Loan_Repayment                   20000 non-null  float64
 7   Insurance                        20000 non-null  float64
 8   Groceries                        20000 non-null  float64
 9   Transport                        20000 non-null  float64
 10  Eating_Out                       20000 non-null  float64
 11  Entertainment                    20000 non-null  float64
 12  Utilities                        20000 non-null  float64
 13  Healthcare                       20000 non-null  float64
 14  Education                        20000 non-null  float64
 15  Miscellaneous                    20000 non-null  float64
 16  Desired_Savings_Percentage       20000 non-null  float64
 17  Desired_Savings                  20000 non-null  float64
 18  Disposable_Income                20000 non-null  float64
 19  Potential_Savings_Groceries      20000 non-null  float64
 20  Potential_Savings_Transport      20000 non-null  float64
 21  Potential_Savings_Eating_Out     20000 non-null  float64
 22  Potential_Savings_Entertainment  20000 non-null  float64
 23  Potential_Savings_Utilities      20000 non-null  float64
 24  Potential_Savings_Healthcare     20000 non-null  float64
 25  Potential_Savings_Education      20000 non-null  float64
 26  Potential_Savings_Miscellaneous  20000 non-null  float64
dtypes: float64(23), int64(2), object(2)
memory usage: 4.1+ MB

In [ ]:
data_frame.describe(include='object')

       Occupation City_Tier
count       20000     20000
unique          4         3
top       Retired    Tier_2
freq         5019     10068

In [ ]:
data_frame.shape

(20000, 27)

In [ ]:
data_frame.isnull().sum()

Income                             0
Age                                0
Dependents                         0
Occupation                         0
City_Tier                          0
Rent                               0
Loan_Repayment                     0
Insurance                          0
Groceries                          0
Transport                          0
Eating_Out                         0
Entertainment                      0
Utilities                          0
Healthcare                         0
Education                          0
Miscellaneous                      0
Desired_Savings_Percentage         0
Desired_Savings                    0
Disposable_Income                  0
Potential_Savings_Groceries        0
Potential_Savings_Transport        0
Potential_Savings_Eating_Out       0
Potential_Savings_Entertainment    0
Potential_Savings_Utilities        0
Potential_Savings_Healthcare       0
Potential_Savings_Education        0
Potential_Savings_Miscellaneous    0
dtype: int64

In [ ]:
data_frame[['Income']].describe()

             Income
count  2.000000e+04
mean   4.158550e+04
std    4.001454e+04
min    1.301187e+03
25%    1.760488e+04
50%    3.018538e+04
75%    5.176545e+04
max    1.079728e+06

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
data_frame[['Age']].describe()

                Age
count  20000.000000
mean      41.031450
std       13.578725
min       18.000000
25%       29.000000
50%       41.000000
75%       53.000000
max       64.000000

In [ ]:
data_frame[['Age']].describe()

                Age
count  20000.000000
mean      41.031450
std       13.578725
min       18.000000
25%       29.000000
50%       41.000000
75%       53.000000
max       64.000000

In [ ]:
data_frame[['Age']].value_counts(normalize=True)

Age
47     0.02405
46     0.02305
21     0.02300
34     0.02245
43     0.02240
44     0.02240
40     0.02220
55     0.02215
56     0.02205
59     0.02205
58     0.02200
22     0.02200
61     0.02200
57     0.02195
19     0.02190
37     0.02185
39     0.02180
45     0.02175
53     0.02155
23     0.02150
41     0.02150
27     0.02140
24     0.02140
64     0.02135
35     0.02120
51     0.02120
25     0.02120
38     0.02120
28     0.02105
18     0.02100
63     0.02095
62     0.02095
33     0.02070
20     0.02070
49     0.02065
60     0.02065
30     0.02040
31     0.02030
26     0.02025
29     0.02020
52     0.02020
42     0.02015
48     0.02000
36     0.01950
32     0.01945
50     0.01935
54     0.01900
Name: proportion, dtype: float64

In [ ]:
data_frame.groupby('Age')[['Income']].mean().sort_values(by='Age')

           Income
Age
18   42693.958699
19   41119.464152
20   41138.458234
21   42093.026955
22   42292.638448
23   43929.269124
24   43339.961352
25   40433.637275
26   41423.269375
27   40031.678842
28   40481.137124
29   44014.925164
30   39057.861676
31   42182.054031
32   40846.693940
33   44528.858202
34   38843.768895
35   43417.264831
36   41694.219379
37   39864.216759
38   40865.678253
39   42989.970280
40   43346.301386
41   41219.050511
42   40225.185873
43   41643.692710
44   39407.815162
45   39691.743501
46   43946.369293
47   44348.726011
48   41146.135002
49   43335.422431
50   42468.562003
51   40052.275891
52   42125.227164
53   41040.146373
54   40154.068359
55   42638.621513
56   40272.148819
57   42558.509818
58   40199.338098
59   40789.121052
60   44346.428924
61   42812.884988
62   39452.679546
63   41627.293925
64   38031.268048

In [ ]:
data_frame.groupby('Age')[['Income']].mean().sort_values(by='Income')

           Income
Age
64   38031.268048
34   38843.768895
30   39057.861676
44   39407.815162
62   39452.679546
45   39691.743501
37   39864.216759
27   40031.678842
51   40052.275891
54   40154.068359
58   40199.338098
42   40225.185873
56   40272.148819
25   40433.637275
28   40481.137124
59   40789.121052
32   40846.693940
38   40865.678253
53   41040.146373
19   41119.464152
20   41138.458234
48   41146.135002
41   41219.050511
26   41423.269375
63   41627.293925
43   41643.692710
36   41694.219379
21   42093.026955
52   42125.227164
31   42182.054031
22   42292.638448
50   42468.562003
57   42558.509818
55   42638.621513
18   42693.958699
61   42812.884988
39   42989.970280
49   43335.422431
24   43339.961352
40   43346.301386
35   43417.264831
23   43929.269124
46   43946.369293
29   44014.925164
60   44346.428924
47   44348.726011
33   44528.858202

In [ ]:
data_frame.isnull()

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Desired_Savings,Disposable_Income,Potential_Savings_Groceries,Potential_Savings_Transport,Potential_Savings_Eating_Out,Potential_Savings_Entertainment,Potential_Savings_Utilities,Potential_Savings_Healthcare,Potential_Savings_Education,Potential_Savings_Miscellaneous
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
data_frame.isna().sum()/len(data_frame)*100

Income                             0.0
Age                                0.0
Dependents                         0.0
Occupation                         0.0
City_Tier                          0.0
Rent                               0.0
Loan_Repayment                     0.0
Insurance                          0.0
Groceries                          0.0
Transport                          0.0
Eating_Out                         0.0
Entertainment                      0.0
Utilities                          0.0
Healthcare                         0.0
Education                          0.0
Miscellaneous                      0.0
Desired_Savings_Percentage         0.0
Desired_Savings                    0.0
Disposable_Income                  0.0
Potential_Savings_Groceries        0.0
Potential_Savings_Transport        0.0
Potential_Savings_Eating_Out       0.0
Potential_Savings_Entertainment    0.0
Potential_Savings_Utilities        0.0
Potential_Savings_Healthcare       0.0
Potential_Savings_Education        0.0
Potential_Savings_Miscellaneous    0.0
dtype: float64

In [ ]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 27 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Income                           20000 non-null  float64
 1   Age                              20000 non-null  int64
 2   Dependents                       20000 non-null  int64
 3   Occupation                       20000 non-null  object
 4   City_Tier                        20000 non-null  object
 5   Rent                             20000 non-null  float64
 6   Loan_Repayment                   20000 non-null  float64
 7   Insurance                        20000 non-null  float64
 8   Groceries                        20000 non-null  float64
 9   Transport                        20000 non-null  float64
 10  Eating_Out                       20000 non-null  float64
 11  Entertainment                    20000 non-null  float64
 12  Utilities                        20000 non-null  float64
 13  Healthcare                       20000 non-null  float64
 14  Education                        20000 non-null  float64
 15  Miscellaneous                    20000 non-null  float64
 16  Desired_Savings_Percentage       20000 non-null  float64
 17  Desired_Savings                  20000 non-null  float64
 18  Disposable_Income                20000 non-null  float64
 19  Potential_Savings_Groceries      20000 non-null  float64
 20  Potential_Savings_Transport      20000 non-null  float64
 21  Potential_Savings_Eating_Out     20000 non-null  float64
 22  Potential_Savings_Entertainment  20000 non-null  float64
 23  Potential_Savings_Utilities      20000 non-null  float64
 24  Potential_Savings_Healthcare     20000 non-null  float64
 25  Potential_Savings_Education      20000 non-null  float64
 26  Potential_Savings_Miscellaneous  20000 non-null  float64
dtypes: float64(23), int64(2), object(2)
memory usage: 4.1+ MB

In [ ]:
data_frame.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Income,20000.0,41585.496104,40014.540538,1301.187333,17604.875957,30185.383480,51765.446460,1.079728e+06
Age,20000.0,41.031450,13.578725,18.000000,29.000000,41.000000,53.000000,6.400000e+01
Dependents,20000.0,1.995950,1.417616,0.000000,1.000000,2.000000,3.000000,4.000000e+00
Rent,20000.0,9115.494629,9254.228188,235.365692,3649.422246,6402.751824,11263.940492,2.159457e+05
Loan_Repayment,20000.0,2049.800292,4281.789941,0.000000,0.000000,0.000000,2627.142320,1.230807e+05
Insurance,20000.0,1455.028761,1492.938435,30.002012,580.204749,1017.124681,1787.160895,3.873493e+04
Groceries,20000.0,5205.667493,5035.953689,154.078240,2165.426419,3741.091535,6470.892718,1.198169e+05
Transport,20000.0,2704.466685,2666.345648,81.228584,1124.578012,1933.845509,3360.597508,8.186150e+04
Eating_Out,20000.0,1461.856982,1481.660811,39.437523,581.011801,1029.109726,1807.075251,3.440610e+04
Entertainment,20000.0,1448.853658,1489.019270,45.421469,581.632906,1020.198376,1790.104082,3.866737e+04
Utilities,20000.0,2504.976953,2522.981880,75.429414,1017.670366,1766.474869,3103.723308,5.372544e+04
Healthcare,20000.0,1663.081794,1628.163024,53.500761,684.364440,1189.203827,2057.082277,3.600153e+04
Education,20000.0,2498.348422,3098.438166,0.000000,611.682170,1701.901075,3311.705122,8.166509e+04
Miscellaneous,20000.0,830.553181,845.019922,20.503223,323.626896,579.078393,1025.195018,1.585636e+04
Desired_Savings_Percentage,20000.0,9.804183,3.903858,5.000042,6.940423,8.898622,11.877171,2.499878e+01
Desired_Savings,20000.0,4982.878416,7733.468188,0.000000,1224.932636,2155.356763,6216.309609,2.455045e+05
Disposable_Income,20000.0,10647.367257,11740.637289,-5400.788673,3774.894323,7224.890977,13331.950716,3.770602e+05
Potential_Savings_Groceries,20000.0,912.197183,1038.884968,16.575501,317.811000,607.038735,1128.681837,3.489464e+04
Potential_Savings_Transport,20000.0,473.042650,537.222853,8.268076,161.913751,307.045856,588.419602,1.227326e+04
Potential_Savings_Eating_Out,20000.0,254.963280,296.047943,3.797926,84.506870,164.927660,313.398240,5.573036e+03
Potential_Savings_Entertainment,20000.0,254.031058,299.973590,3.121610,84.562090,164.740232,310.927935,6.222201e+03
Potential_Savings_Utilities,20000.0,436.332808,503.200658,6.200297,148.013618,285.739582,538.983703,8.081800e+03
Potential_Savings_Healthcare,20000.0,41.524964,53.152458,0.001238,11.037421,25.202124,52.353736,1.394531e+03
Potential_Savings_Education,20000.0,62.417083,98.842656,0.000000,4.926210,33.127987,80.946145,3.647244e+03
Potential_Savings_Miscellaneous,20000.0,144.904987,169.160951,2.091973,47.637307,93.090257,178.257981,4.637951e+03

In [ ]:
# To expand e scientific notation
pd.set_option('display.float_format', '{:.2f}'.format)

In [ ]:
data_frame.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Income,20000.00,41585.50,40014.54,1301.19,17604.88,30185.38,51765.45,1079728.37
Age,20000.00,41.03,13.58,18.00,29.00,41.00,53.00,64.00
Dependents,20000.00,2.00,1.42,0.00,1.00,2.00,3.00,4.00
Rent,20000.00,9115.49,9254.23,235.37,3649.42,6402.75,11263.94,215945.67
Loan_Repayment,20000.00,2049.80,4281.79,0.00,0.00,0.00,2627.14,123080.68
Insurance,20000.00,1455.03,1492.94,30.00,580.20,1017.12,1787.16,38734.93
Groceries,20000.00,5205.67,5035.95,154.08,2165.43,3741.09,6470.89,119816.90
Transport,20000.00,2704.47,2666.35,81.23,1124.58,1933.85,3360.60,81861.50
Eating_Out,20000.00,1461.86,1481.66,39.44,581.01,1029.11,1807.08,34406.10
Entertainment,20000.00,1448.85,1489.02,45.42,581.63,1020.20,1790.10,38667.37
Utilities,20000.00,2504.98,2522.98,75.43,1017.67,1766.47,3103.72,53725.44
Healthcare,20000.00,1663.08,1628.16,53.50,684.36,1189.20,2057.08,36001.53
Education,20000.00,2498.35,3098.44,0.00,611.68,1701.90,3311.71,81665.09
Miscellaneous,20000.00,830.55,845.02,20.50,323.63,579.08,1025.20,15856.36
Desired_Savings_Percentage,20000.00,9.80,3.90,5.00,6.94,8.90,11.88,25.00
Desired_Savings,20000.00,4982.88,7733.47,0.00,1224.93,2155.36,6216.31,245504.49
Disposable_Income,20000.00,10647.37,11740.64,-5400.79,3774.89,7224.89,13331.95,377060.22
Potential_Savings_Groceries,20000.00,912.20,1038.88,16.58,317.81,607.04,1128.68,34894.64
Potential_Savings_Transport,20000.00,473.04,537.22,8.27,161.91,307.05,588.42,12273.26
Potential_Savings_Eating_Out,20000.00,254.96,296.05,3.80,84.51,164.93,313.40,5573.04
Potential_Savings_Entertainment,20000.00,254.03,299.97,3.12,84.56,164.74,310.93,6222.20
Potential_Savings_Utilities,20000.00,436.33,503.20,6.20,148.01,285.74,538.98,8081.80
Potential_Savings_Healthcare,20000.00,41.52,53.15,0.00,11.04,25.20,52.35,1394.53
Potential_Savings_Education,20000.00,62.42,98.84,0.00,4.93,33.13,80.95,3647.24
Potential_Savings_Miscellaneous,20000.00,144.90,169.16,2.09,47.64,93.09,178.26,4637.95

In [ ]:
count = data_frame[data_frame['Age'] < 30].shape[0]

In [ ]:
print(f"Number of records where Age < 30: {count}")

Number of records where Age < 30: 5112

In [ ]:
# Drop records where Age >=30
data_frame = data_frame[data_frame['Age'] < 30]

# Save the cleaned dataset
data_frame.to_csv('filtered_data.csv', index=False)

# Download the new file
from google.colab import files
files.download('filtered_data.csv')

# Display the first few rows
data_frame.head()

,Income,Age,Dependents,Occupation,City_Tier,Rent,Loan_Repayment,Insurance,Groceries,Transport,...,Desired_Savings,Disposable_Income,Potential_Savings_Groceries,Potential_Savings_Transport,Potential_Savings_Eating_Out,Potential_Savings_Entertainment,Potential_Savings_Utilities,Potential_Savings_Healthcare,Potential_Savings_Education,Potential_Savings_Miscellaneous
3,101455.600247,21,0,Self_Employed,Tier_3,15218.340037,6809.441427,4889.418087,14690.149363,7106.130005,...,16694.965136,31617.953615,1875.932770,762.020789,1241.017448,320.190594,1389.815033,193.502754,0.000000,296.041183
13,6492.016466,22,3,Retired,Tier_3,973.802470,0.000000,184.243341,955.499426,494.824192,...,464.290917,1880.926140,180.471308,38.254592,59.828536,49.160505,60.742440,3.924078,20.417945,46.559239
17,38574.647021,21,4,Professional,Tier_2,7714.929404,0.000000,1838.336035,5126.823467,2614.478029,...,2666.085960,10612.576690,862.854091,202.782785,217.659400,113.219422,435.103427,6.837143,41.434760,179.796583
26,11946.071980,19,4,Student,Tier_2,2389.214396,0.000000,413.296293,1363.786116,641.888253,...,670.453708,4147.829434,322.020175,62.931168,133.383500,111.362113,101.629078,19.872215,0.222671,15.691375
35,11296.833460,27,2,Retired,Tier_2,2259.366692,0.000000,380.878040,1382.734509,763.560869,...,979.960454,3287.890795,307.054384,98.826452,28.283275,73.618090,67.238552,13.699792,9.803052,60.749555

In [ ]:
#Importing pandas library
import pandas as pd
#Loading data into a DataFrame
filtered_data=pd.read_csv('/content/drive/MyDrive/SDGP Implementation/filtered_data.csv')

In [ ]:
filtered_data.shape

(5112, 27)

In [ ]:
filtered_data[['Age']].describe()

               Age
count  5112.000000
mean     23.445618
std       3.431553
min      18.000000
25%      21.000000
50%      23.000000
75%      26.000000
max      29.000000

In [ ]:
filtered_data.dropna

<bound method DataFrame.dropna of              Income  Age  Dependents     Occupation City_Tier          Rent  \
0     101455.600247   21           0  Self_Employed    Tier_3  15218.340037
1       6492.016466   22           3        Retired    Tier_3    973.802470
2      38574.647021   21           4   Professional    Tier_2   7714.929404
3      11946.071980   19           4        Student    Tier_2   2389.214396
4      11296.833460   27           2        Retired    Tier_2   2259.366692
...             ...  ...         ...            ...       ...           ...
5107   64797.755664   29           1        Student    Tier_1  19439.326699
5108   45208.132385   22           2        Student    Tier_1  13562.439716
5109   14380.461643   26           0  Self_Employed    Tier_2   2876.092329
5110   90295.772638   21           1        Student    Tier_2  18059.154528
5111  118157.817240   27           2   Professional    Tier_1  35447.345172

      Loan_Repayment    Insurance     Groceries    Transport  ...  \
0        6809.441427  4889.418087  14690.149363  7106.130005  ...
1           0.000000   184.243341    955.499426   494.824192  ...
2           0.000000  1838.336035   5126.823467  2614.478029  ...
3           0.000000   413.296293   1363.786116   641.888253  ...
4           0.000000   380.878040   1382.734509   763.560869  ...
...              ...          ...           ...          ...  ...
5107     7509.763551  2564.163762   8501.877012  3485.020199  ...
5108        0.000000   980.292173   4805.454862  3199.443224  ...
5109        0.000000   443.629398   2016.627529   933.513130  ...
5110        0.000000  2770.589626  13118.222419  4633.108332  ...
5111    12345.910538  4735.672471  16392.438426  8248.242279  ...

      Desired_Savings  Disposable_Income  Potential_Savings_Groceries  \
0        16694.965136       31617.953615                  1875.932770
1          464.290917        1880.926140                   180.471308
2         2666.085960       10612.576690                   862.854091
3          670.453708        4147.829434                   322.020175
4          979.960454        3287.890795                   307.054384
...               ...                ...                          ...
5107      6705.784400        6821.408589                  1814.875532
5108      5746.751706        9070.221276                  1140.709244
5109      1125.042329        5388.488847                   174.762586
5110     10613.589598       30725.175170                  3854.823822
5111     10603.684814       10603.684814                  3217.771594

      Potential_Savings_Transport  Potential_Savings_Eating_Out  \
0                      762.020789                   1241.017448
1                       38.254592                     59.828536
2                      202.782785                    217.659400
3                       62.931168                    133.383500
4                       98.826452                     28.283275
...                           ...                           ...
5107                   795.427369                    196.749053
5108                   334.204130                    116.963636
5109                   121.694051                     93.375580
5110                   359.602765                    911.269461
5111                  2265.865033                    726.247719

      Potential_Savings_Entertainment  Potential_Savings_Utilities  \
0                          320.190594                  1389.815033
1                           49.160505                    60.742440
2                          113.219422                   435.103427
3                          111.362113                   101.629078
4                           73.618090                    67.238552
...                               ...                          ...
5107                       414.970477                   576.742852
5108                       502.311982                   574.811605
5109                        77.563110                   138.649996
5110                       424.064224                  1555.548024
5111                       273.912367                   859.230004

      Potential_Savings_Healthcare  Potential_Savings_Education  \
0                       193.502754                     0.000000
1                         3.924078                    20.417945
2                         6.837143                    41.434760
3                        19.872215                     0.222671
4                        13.699792                     9.803052
...                            ...                          ...
5107                     10.722315                    65.203003
5108                      1.951078                   153.845268
5109                     14.154576                     0.000000
5110                    129.655981                   239.445622
5111                     98.961780                    92.189012

      Potential_Savings_Miscellaneous
0                          296.041183
1                           46.559239
2                          179.796583
3                           15.691375
4                           60.749555
...                               ...
5107                       390.007272
5108                       188.809833
5109                        30.832802
5110                       351.436046
5111                       569.811212

[5112 rows x 27 columns]>

In [ ]:
filtered_data.shape

(5112, 27)